@startuml erd_airline_reservation_logique

entity Pays {
    codeISO
    descriptionFr
}

entity Aeroport {
    code
    nom
    ville
    pays
}

entity OccurrenceVol {
    dateDepartPrevue
    dateArriveePrevue
    dateDepartReelle
    dateArriveeReelle
}

entity Vol {
    numero
    dureeMoyenne
    aeroportDepart
    aeroportArrivee
}

entity DonneesTranspondeur {
    date
    coordonnees
}

entity Avion {
    marque
    numero
    type
    nombrePlaces
    dateAchat
}

entity RevisionAvion {
    date
    peutVoler
    type 
    ' https://fr.wikipedia.org/wiki/Visites_de_maintenance_des_avions
    ' A : / mois ou 500h de vol
    ' C : 
}

entity CompagnieAerienne {
    nom
    abreviation
}

entity Voyage {
    prix
}

entity Billet {
    rang
    siege
    classe
}

entity Passager {
    nom
    prenom
    dateNaissance
    age
    numeroPassport
    dateAutorisationParentale
}

Vol }o--|| Aeroport: arrive
Vol }o--|| Aeroport: part
'Vol }o--|| Avion: a
Vol ||--o{ OccurrenceVol: est réalisé

Avion }o--|| CompagnieAerienne: appartient

Billet }o--|| Voyage: est composé de
Billet }o--|| OccurrenceVol: billet pour

Voyage }o--|| Passager: achète

Aeroport }o--|| Pays: est domicilié

OccurrenceVol ||--o{ DonneesTranspondeur: transmet des données
OccurrenceVol }o--|| Avion: a


RevisionAvion }o--|| Avion: a été révisé

@enduml
